image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:latest .
  artifacts:
    paths:
      - node_modules/
      - dist/

testing_testing:
  stage: test
  script: 
    - echo "TODO testing"

deploy_push_docker:
  stage: deploy
  script:
    - docker push $CI_REGISTRY_IMAGE:latest
